### List homepage /
GET http://localhost:5000/

### Create a new user
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "name":"Burak",
  "lastname":"Kepuc",
  "email": "burak@test.com",
  "password":"test123"
}

### Login user
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "burak@test.com",
  "password":"test123"
}