### List homepage /
GET http://localhost:5000/

### Create a new user
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "name":"Burak",
  "lastname":"Kepuc",
  "email": "burak@test.com",
  "password":"test123"
}

### Login user
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "burakkepuc.1996@gmail.com",
  "password":"test123"
}

### Forget Password user
POST http://localhost:5000/api/forget-password
Content-Type: application/json

{
  "email": "burakkepuc.1996@gmail.com"
}

### Reset Code Check
POST http://localhost:5000/api/reset-code-check
Content-Type: application/json

{
  "email": "burakkepuc.1996@gmail.com",
  "code":"828436"
}

### Reset Password
POST http://localhost:5000/api/reset-password
Content-Type: application/json

{
  "password": "test123",
  "tempToken":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Njk2ZWQ1YTc2OTU1MWIwMDQ2ZDU5MGUiLCJpYXQiOjE3MjE2MTE0NjYsImV4cCI6MTcyMjIxNjI2Nn0.6TSqFoJ1XpN_QAxj4LJx9Em6YgNgJB_E7qMs-lb4SfxiHc-2KtFUkfnELTUnAp6Q_9LSpgsGYMvzuGlWEtHafQ"
}


### Access Protected Resource
GET http://localhost:5000/api/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Njk2ZWQ1YTc2OTU1MWIwMDQ2ZDU5MGUiLCJuYW1lIjoiQnVyYWsiLCJlbWFpbCI6ImJ1cmFrQHRlc3QuY29tIiwiaWF0IjoxNzIxNDI5NTI2LCJleHAiOjE3MjIwMzQzMjZ9.SftyGXaAY0Gl9ufxllHsr12Of2TahIXrwrn3KO3-66j95YuvV13X8LKbFtv-vCx1qRFff_Texn833svz7pWEUA